### PR TITLE
#104: Optimised query for getPaletteRelations

### LINKED ISSUE #104: Palette generation is too slow
When a domain model is deployed to system modeller (including an initial deployment), system modeller has to process the domain model bundle (a zipfile containing the domain model NQ file, a set of icons, and a mapping from asset types to icons). This takes an annoyingly long time.

The problem is especially noticeable to domain model developers, who need to upload successive changes to test new features, and potentially revert to old versions for regression testing, etc. Waiting many minutes on each occasion can add up to a lot of lost time.

The problem seems to be in the generation of links. I assume the code is creating a complete list of (resource asset type)-(relationship type)-(target asset type) relations that users should be able to create, which would involve using inheritance to find all combinations.

Ideally this area of the code should be optimised before we try to involve more people in domain model development.

### PR DESCRIPTION
**Pull request by kenmeacham**

### CODE REVIEW

**Review by mike1813 — APPROVED** [review]
I haven't tested this change, but I did review the code changes and compared the JSON output files in detail.

There are a few things going on here that could be factored in, but at this stage I propose we accept the changes and merge them.

The aspects we might want to change later stem from two unrelated issues, one a bug, the other a characteristic of all domain models.

At present every relationship is indeed defined as a type of owl:ObjectProperty, and all have two properties related to this issue. The first is core:isAssertable (sic), a boolean set to 'true' if the relationship can be asserted. This was added to assets and relationships when it became clear some would be used only in construction, and users should not be able to create them because the construction sequence logic assumed they would only be created by construction patterns. The other is core:hidden, also boolean, and set to 'true' if the relationship should be omitted from the U/I display. This was added because a system model with lots of visible relationships can be confusing, and leaving out some of them makes sense, especially for relationship types that are usually added by construction.

Unfortunately, the person who implemented the U/I feature to 'hide' relationships thought that core:hidden = 'true' meant the relationship type should be hidden in the drop-down for selecting which relationship to create between two assets. What they implemented treats core:hidden = 'true' as equivalent to core:isAssertable = 'false', and there is no separate feature for concealing relationships in the U/I. This is really a bug - the description of core:hidden in core.rdf and the behaviour of the system-modeller code is not consistent with the expected meaning of core:hidden and core:isAssertable. However, the system-modeller code is consistent with the buggy core.rdf, and we will eventually need to replace core.rdf completely, so I see little benefit in fixing this now.

The one thing that might be worth changing now is that the 'OPTIONAL' keyword in the SPARQL query shouldn't be necessary, because these two properties exist for every relationship type. Making that change should make no difference to the result, but may affect performance - although I don't know whether it would make the code faster or slower.

The other point worth noting is that asset classes fall into two subsets:

- Asset classes that can be asserted or constructed, which I sometimes call 'concrete' asset classes in domain model descriptions.
- Asset classes that can be neither asserted nor constructed.

In principle, only the first type of assets can exist in system models, because the only way they can get into a system model is via assertion or construction. The remaining asset classes are used in matching patterns to specify which of the concrete asset types can fulfil each role in the matching pattern. For example, in a matching pattern you can specify that a role must be fulfilled by an asset in the class domain:Host, and that would mean the role could be matched by system model assets in numerous concrete asset subclasses including VM, Server, Workstation or IoT Thing. But if you create a system model asset of type domain:Host, too many aspects are undefined, e.g., whether it is physical or virtual, and if physical, whether it has a user interface, whether it is fixed, mobile or attached to a person or a physical location, etc.

Obviously, if only some asset classes can exist in a system model, then relationships can only exist between assets in those classes, so the amount of relationship type data we need in palette.json is far less than we may think. However, having some entries we don't really need probably isn't doing any harm, so this too can be left 'as is', at least for now.

**Comment by kenmeacham** [comment]
> I haven't tested this change, but I did review the code changes and compared the JSON output files in detail.

Thanks. It would be good to understand (at some point) why there are a few discrepencies..

> There are a few things going on here that could be factored in, but at this stage I propose we accept the changes and merge them.

I have now merged in the branch, after some quick fixes (see below)

> The aspects we might want to change later stem from two unrelated issues, one a bug, the other a characteristic of all domain models.

These should ideally migrate to a new issue, if they are not directly related to the palette generation

> At present every relationship is indeed defined as a type of owl:ObjectProperty, and all have two properties related to this issue. The first is core:isAssertable (sic), a boolean set to 'true' if the relationship can be asserted. This was added to assets and relationships when it became clear some would be used only in construction, and users should not be able to create them because the construction sequence logic assumed they would only be created by construction patterns. The other is core:hidden, also boolean, and set to 'true' if the relationship should be omitted from the U/I display. This was added because a system model with lots of visible relationships can be confusing, and leaving out some of them makes sense, especially for relationship types that are usually added by construction.

Only the core:hidden property is queried for the palette. Any "hidden" relations are not indluded in the links. Are you saying that we should also examine the core:isAssertable properties for the palette generation?

> Unfortunately, the person who implemented the U/I feature to 'hide' relationships thought that core:hidden = 'true' meant the relationship type should be hidden in the drop-down for selecting which relationship to create between two assets. 

Like I said, the links are not included in the generated palette (see comment above). Is this wrong?

> What they implemented treats core:hidden = 'true' as equivalent to core:isAssertable = 'false', and there is no separate feature for concealing relationships in the U/I. This is really a bug - the description of core:hidden in core.rdf and the behaviour of the system-modeller code is not consistent with the expected meaning of core:hidden and core:isAssertable. However, the system-modeller code is consistent with the buggy core.rdf, and we will eventually need to replace core.rdf completely, so I see little benefit in fixing this now.

I can only see core:isAssertable in queries related to Control Sets> Slightly confused how the above relates to the palette generation. Maybe we can discuss sometime?

> The one thing that might be worth changing now is that the 'OPTIONAL' keyword in the SPARQL query shouldn't be necessary, because these two properties exist for every relationship type. Making that change should make no difference to the result, but may affect performance - although I don't know whether it would make the code faster or slower.

I have taken out the OPTIONAL keyword from the query that gets the palette relations. Fortunately this has had no effect on the results (expected if there is a value for each relation), and it also doesn't affect the performance. So this has been committed to the branch prior to merge.

> The other point worth noting is that asset classes fall into two subsets:
> 
>     * Asset classes that can be asserted or constructed, which I sometimes call 'concrete' asset classes in domain model descriptions.
> 
>     * Asset classes that can be neither asserted nor constructed.
> 
> 
> In principle, only the first type of assets can exist in system models, because the only way they can get into a system model is via assertion or construction. The remaining asset classes are used in matching patterns to specify which of the concrete asset types can fulfil each role in the matching pattern. For example, in a matching pattern you can specify that a role must be fulfilled by an asset in the class domain:Host, and that would mean the role could be matched by system model assets in numerous concrete asset subclasses including VM, Server, Workstation or IoT Thing. But if you create a system model asset of type domain:Host, too many aspects are undefined, e.g., whether it is physical or virtual, and if physical, whether it has a user interface, whether it is fixed, mobile or attached to a person or a physical location, etc.
> 
> Obviously, if only some asset classes can exist in a system model, then relationships can only exist between assets in those classes, so the amount of relationship type data we need in palette.json is far less than we may think. However, having some entries we don't really need probably isn't doing any harm, so this too can be left 'as is', at least for now.

Point noted!

**Comment by mike1813** [comment]
On why we get some differences between the old and new queries.

I reordered the 'new' JSON file so it matched the old one, and found the only differences were that some extra links were being added. They corresponded to the following domain and range definitions:

- Host-atHost-DataPool
- DataPath-dataPathFor-DataPool
- USBDevice-pairsViaUSB-USBHost
- MobileClient-pairsViaUSB-USBHost
- Notebook-pairsViaUSB-USBHost
- Human-interactsWith-InteractiveHost

None of these were generated before, because either the domain or the range is one of those 'non-concrete' asset classes, which in our current domain model are 'overlays' on the asset class hierarchy and not themselves subclasses of core:Asset. The best way to explain what I mean by an overlay is by an example. Suppose we have the following class hierarchy:

- domain:A suBclassOf core:Asset
- domain:B suBclassOf core:Asset
- domain:C suBclassOf domain:B
- domain:D suBclassOf domain:B
- domain:E suBclassOf core:Asset

Then we realise that A, D and E all share some characteristic, so we create a common parent class P for that:

- domain:A subClassOf domain:P
- domain:D subClassOf domain:P
- domain:E subClassOf domain:P

So now A, D and E have multiple parent classes, one representing their position in the main hierarchy and this extra one that codes for this shared characteristic. However, P is not a subclass of core:Asset. It isn't part of the hierarchy - it is an overlay classifier, that brings together subclasses from different branches of the hierarchy.

In the current network domain model domain:DataPool, domain:USBHost, domain:USBDevice, domain:InteractiveHost (and its subclass domain:ConsoleHost) are all overlay classifiers and not subclasses of core:Asset. In the old query, ?domain and ?range both had to be subclasses of core:Asset, so these references to overlay parent classes were excluded.

Two things are still a bit odd. Firstly, some of these extra link types are not assertible, so they have both core:isAssertable = false and core:hidden = true, although some other non-assertible link types don't appear. Secondly, the ones that do appear have at least one concrete asset subclass in at least one end of the link.

I suspect what is happening is that links get returned regardless of the value of their core:hidden (or equivalently, core:isAssertable) properties. Then the code that translates the query results into JSON applies some filtering. It looks like that filtering depends on whether at least one end of the link has at least one concrete asset. The new query doesn't look for that, so I suspect the code may get this from the results of the previous query that looked for concrete assets from which to create the asset palette.

@kenmeacham : I propose we move all this stuff to a new issue. See next comment.

**Comment by mike1813** [comment]
I created a separate issue regarding the use of filters in the SPARQL query (issue #224). The question of whether to base this on core:hidden or core:isAssertable can then be included in the new issue, along with the question of whether we should try to limit the palette to relationships between concrete assets.

Overlay parent classes that are not subclasses of core:Asset are obviously not 'concrete' (as discussed above). However, there are some subclasses of core:Asset that are also not concrete (like the example of domain:Host, also discussed above). Restricting link palette information to relationships between concrete assets is therefore not simple, as discussed in the new issue.

My recommendation (which I added in a comment on the new issue) is to do nothing about any of this unless we see it is causing problems.

**Pull request merged**
