### PR TITLE
94 add way to reveal hidden trustworthiness attributes in UI

### PR DESCRIPTION
**Pull request by kenmeacham**

### CODE REVIEW

**Review by scp93ch — COMMENTED** [review]
You've deleted more lines of code than you've added!

All seems to work fine.

I have a problem with the label "Only visible attributes". It's a bit weird in that you can then show the "invisible" ones if you untick it. They are all then literally "visible" and checking the box to show "only visible attributes" then hides some.

I think it would be better to use a term such as "Primary attributes" and "Secondary attributes". I would suggest reversing the logic and having an unchecked tick-box with the label "Secondary attributes". Ticking it would then display the full list.

**Comment by scp93ch** [comment]
As discussed in the call just now, let's change it to "Hidden attributes", unticked by default. Its still a bit weird as when you tick it they are not hidden are they? Anyway, it would be better than the current label/logic.

**Comment by kenmeacham** [comment]
Or "Show hidden attributes" ?

**Comment by kenmeacham** [comment]
New look:

image

Just running tests on this..

**Review by scp93ch — APPROVED** [review]
Looks good

**Pull request merged**
