### PR TITLE
101 domain model control over asset palette categorization

### LINKED ISSUE #101: Domain model control over asset palette categorization
At present, the palette of asset types displayed in the system-modeller editor window is created by finding the subclass of `core:asset` of which each assertible asset class is a descendent. This subclass of `core:asset` is taken as the palette category in which to display the asset type in the palette.

This means that (for example) every type of Host must be displayed together in the Hosts palette group, every Process in the Processes palette group, and so forth. That isn't always the best option.

For example, the domain-network submodel for Cloud Management currently uses specialised Host subclasses to represent Kubernetes Master, Worker, Pod and Container components, Process subclasses for the Kubernetes API Server and Ingress proxy, and a NetworkAsset subclass representing the ClusterIP overlay network between the Master VM and running Pods. Ideally, those asset classes would be in a separate 'Cloud' group.

The domain model does contain a mechanism to handle this. Alongside the asset class hierarchy descended from `core:Asset` there is a separate 'overlay' hierarchy descended from `core:PaletteType`. So setting `?category rdfs:subClassOf core:PaletteType` would provide a means for the domain model to specify a palette grouping based on any criterion.

At present, each assertible asset has only one palette 'category'. That restriction can be respected by domain modellers at least to begin with. Later, we may want to allow each asset to appear in more than one 'category', but this may require more extensive changes, so can be left as a separate issue.

### PR DESCRIPTION
**Pull request by kenmeacham**

### CODE REVIEW

**Comment by kenmeacham** [comment]
@mike1813 - I've put you as reviewer for this pull request, as you understand it the best. In the end, it is only a minor fix to the SPARQL query, an addition to the core model and a fix to the unit test. See issue #101 for screenshots of how it looks now, so no need to spin it up yourself. See also a question about the fix to the core model.

**Review by mike1813 — COMMENTED** [review]
@kenmeacham : I suggest two small changes before we merge this:

- Make core#PaletteType a subclass of #AtomicThing, which is the base class for core#Asset.
- Delete the lines that add typeLabel in the report generator, rather than commenting them.

The first change is just so core#PaletteType looks as similar to core#Asset as possible. The properties are the same for #CompositeThing and #AtomicThing so it should work as it is. The only reason to switch to #AtomicThing is so it will still work if we ever need to switch from core#Asset to core#PaletteType in some other query.

The second change is just to avoid retaining old code we don't really need. It doesn't look like we'll ever want to reinstate the commented lines, so keeping them in just detracts from the code readability.

**Comment by kenmeacham** [comment]
> @kenmeacham : I suggest two small changes before we merge this:
> 
>     * Make core#PaletteType a subclass of #AtomicThing, which is the base class for core#Asset.
> 
>     * Delete the lines that add typeLabel in the report generator, rather than commenting them.
> 
> 
> The first change is just so core#PaletteType looks as similar to core#Asset as possible. The properties are the same for #CompositeThing and #AtomicThing so it should work as it is. The only reason to switch to #AtomicThing is so it will still work if we ever need to switch from core#Asset to core#PaletteType in some other query.
> 
> The second change is just to avoid retaining old code we don't really need. It doesn't look like we'll ever want to reinstate the commented lines, so keeping them in just detracts from the code readability.

OK. I've made the suggested changes. All seems to still work as expected. You should be able to just approve this now, so I can do the merge.

**Review by mike1813 — APPROVED** [review]
Looks good.

**Pull request merged**
